### ISSUE TITLE
Fix bug on chrome for Lightning Development (Dusty) page

### ISSUE THREAD

**Issue by abitcoinperson** [OpenSats/website#81] opened 2023-05-02 23:26 UTC
Not sure if this is on just iOS or also on Android, and perhaps across other browsers other than chrome...

But on iOS using chrome the https://opensats.org/projects/dusty page is not mobile optimized: 

![image](https://user-images.githubusercontent.com/8769819/235806246-e23493e6-0883-42ff-a5cc-8856a3d14db5.png)

**Comment by dergigi** [comment] 2023-05-03 08:15
Duplicate of #43

**Closed by dergigi** 2023-05-03 08:15 UTC
Labels: bug, duplicate, good first issue
